### ISSUE TITLE
bit-endian => big-endian

### ISSUE THREAD

**Issue by fisxoj** [marcoheisig/numpy-file-format#1]
https://github.com/marcoheisig/numpy-file-format/blob/7e55e40812bb434dc340ce20308245676ee71097/code/dtypes.lisp#L5

:wave: Was just poking through the repo after I saw the project listed in this month's quicklisp dist.  I think this is probably a typo!

**Comment by marcoheisig** [comment]
Fixed in 36b15eb.  Thanks for reporting!
